name: Workflow

on:
  push:
    branches:
      - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Análisis de seguridad
        uses: Sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONARCLOUD_ORG: laboratorio-final-devsecops
          SONARCLOUD_PROJECT: Laboratorio-Final-DevSecOps_Laboratorio-N-R

      - name: Verificar vulnerabilidades
        run: |
          if [ $(sonarcloud status -f) -eq 1 ]; then
            echo "Se detectaron vulnerabilidades altas, medias o críticas."
            exit 1
          fi