name: Workflow
on:
  push: 
    branches:
        - main

jobs:
  SCA:
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Análisis SCA con Dependency Check
      uses: owasp/dependency-check@v6
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        args: --format JSON --out results.json
        fail-on: HIGH,MEDIUM,LOW
    
    - name: Verificar vulnerabilidades
      run: |
        if [ -f results.json ]; then
            vulnerabilities=$(jq '.dependencies[] | select(.vulnerability.severity == "HIGH" or .vulnerability.severity == "MEDIUM" or .vulnerability.severity == "MAJOR")' results.json)
            if [ -n "$vulnerabilities" ]; then
              echo "Se detectaron vulnerabilidades."
              exit 1
            fi
          fi       

    - name: Upload Test Result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck Report
        path: ./reports