name: Workflow 

on:
  push:
    branches:
      - main
  
jobs:
 
  SCA:
    runs-on: ubuntu-latest
    steps: 
  
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        args: >
          --out ./reports
          --failOnCVSS 7
          --enableRetired

    - name: Upload Test Result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck Report
        path: ./reports
      
    - name: Check for vulnerabilities
      run: |
        if grep -q 'CRITICAL\|HIGH\|MEDIUM' dependency-check-report/dependency-check-report.html; then
          echo "Found vulnerabilities: Failing the build"
          exit 1
        else
          echo "No critical, high, or medium vulnerabilities found"
        fi
  
    