name: Workflow
on:
  push: 
    branches:
        - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
            fetch-depth: 0
      - name: Análisis con SonarCloud
        uses: Sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
            SONARCLOUD_ORG: laboratorio-final-devsecops
            SONARCLOUD_PROJECT: Laboratorio-Final-DevSecOps_Laboratorio-N-R
