name: Workflow

on:
  push:
    branches:
      - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Análisis con SonarCloud 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          
        run: |
            -Dsonar.projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R \
            -Dsonar.organization=laboratorio-final-devsecops \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.branch.name=main