name: Workflow
on:
  push: 
    branches:
        - main

jobs:         
    DockerBuild:
      needs: SCA
      runs-on: ubuntu-24.04
      steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: |
          docker build --tag emanuelnunezf/laboratorio-n-r:latest .

      - name: Push Docker
        run: |
          docker push emanuelnunezf/laboratorio-n-r:latest

  DockerScan:
      needs: DockerBuild
      runs-on: ubuntu-24.04
      steps:
    
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Pull Docker
        run: |
          docker pull emanuelnunezf/laboratorio-n-r:latest

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'emanuelnunezf/laboratorio-n-r:latest'
          format: 'table'
          
- name: Triage Discussion
on:
  discussion:
    types: [created]
  workflow_dispatch:
    inputs:
      discussion_num:
        required: true
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/trivy-triage
        with:
          discussion_num: ${{ github.event.inputs.discussion_num }}
