name: Workflow
on:
  push: 
    branches:
        - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
       
      - name: SonarCloud Scan
        uses: Sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        with:
          args: >
              -Dsonar.organization="laboratorio-final-devsecops"
              -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"    
              
      - name: Check Quality Gate Status
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
        
          STATUS=$(curl -s -u $SONAR_TOKEN: \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R" \ | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $STATUS"
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed. Vulnerabilities detected!"
            exit 1
          fi