name: Workflow
on:
  push: 
    branches:
        - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: Sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        with:
          args: >
              -Dsonar.organization="laboratorio-final-devsecops"
              -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"   
  SCA:
    needs: SAST
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        args: >
          --out ./reports
          --failOnCVSS 7
          --enableRetired
          --format JSON --out .dependency-check-report.json
          failOnCVSS: 0.0

    - name: Upload Test Result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck Report
        path: ./reports

    - name: Verificar vulnerabilidades
      run: |
          if [ -f .dependency-check-report.json ]; then
            vulnerabilities=$(jq '.dependencies[] | select(.vulnerability.severity == "LOW" or .vulnerability.severity == "MEDIUM" or .vulnerability.severity == "HIGH")' .dependency-check-report.json)
            if [ -n "$vulnerabilities" ]; then
              echo "Se detectaron vulnerabilidades mínimas, medias y críticas."
              exit 1
            fi
          fi