name: Workflow
on:
  push: 
    branches:
        - feat

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: Sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        with:
          args: >
              -Dsonar.organization=laboratorio-final-devsecops
              -Dsonar.projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R
  
   SCA:
    name: Análisis de dependencia
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -

      - name: Run SCA Analysis
        run: |
          trivy fs --scanners vuln .
          
