name: Workflow
on:
  push:
    branches:
      - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with: 
        args: >
          -Dsonar.organization="laboratorio-final-devsecops"
          -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=lib/
          -Dsonar.tests=tests/
          -Dsonar.test.exclusions=tests/**
          -Dsonar.verbose=true
        
        