name: Desplegar Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Construir imagen de Docker
        run: |
          docker build -t laboratorio-n-r .

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Etiquetar y empujar la imagen
        run: |
          docker tag laboratorio-n-r ${{ secrets.DOCKER_USER }}/laboratorio-n-r
          docker push ${{ secrets.DOCKER_USER }}/laboratorio-n-r