name: Workflow
on:
  push: 
    branches:
        - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: Sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        with:
          args: --fail-on-issue --minimum-severity HIGH
              -Dsonar.organization="laboratorio-final-devsecops"
              -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"   
      
      - name: Verificar vulnerabilidades
        run: |
          if [ -f sonarcloud-report.json ]; then
            vulnerabilities=$(jq '.issues[] | select(.severity == "HIGH" or .severity == "MEDIUM" or .severity == "CRITICAL")' sonarcloud-report.json)
            if [ -n "$vulnerabilities" ]; then
              echo "Se detectaron vulnerabilidades altas, medias o críticas."
              exit 1
            fi
          fi

        

              
  