name: Workflow 

on:
  push:
    branches:
      - main
  
jobs:
 
  SCA:
    runs-on: 24.04

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Dependency-Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env: 
        JAVA_HOME: opt/jdk
      id: Depcheck
      with: 
        project: 'Laboratorio-N-R' 
        format: 'HTML' 
        outputDirectory: 'dependency-check-report' 
        scanPath: './'
    
    - name: Upload Dependency-Check Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: dependency-check-report
    
    - name: Check Dependency-Check Report for Vulnerabilities
      run: |
        if grep -iq "Critical\|High\|Medium" dependency-check-report/dependency-check-report.json; then
            echo "Vulnerabilities found! Failing the build."
            exit 1
        else
          echo "No critical, high, or medium vulnerabilities found."
          fi

